---
title: "lipid-parsing"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lipid-parsing}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Installation of <code>lipidomicsUtils</code>
The <code>lipidomicsUtils</code> package enables to parse lipid shorthand notations and additionally offers several calculation functions. The package can be installed directly from GitHub using functions from <code>devtools</code>.

```{r setup}
# loading required libraries
# use only if package shall be installed
#library(devtools)
#install_github("michaelwitting/lipidomicsUtils", ref = "master")

library(lipidomicsUtils)
```

# Lipid categories

```{r categories}
# example lipid PC(16:0/18:1(9Z)), LMGP01010005
lipid <- "PC(16:0/18:1(9Z)"

# get different lipid categories
get_lipid_category(lipid)
get_lipid_mainclass(lipid)
get_lipid_subclass(lipid)
```


```{r categories2}
# example lipid PC(O-18:0/18:1(9Z)), LMGP01020202
lipid <- "PC(O-18:0/18:1(9Z)"

# get different lipid categories
get_lipid_category(lipid)
get_lipid_mainclass(lipid)
get_lipid_subclass(lipid)
```

```{r categories3}
# example lipid Cer(d18:1/18:1(9Z)), LMSP02010003
lipid <- "Cer(d18:1/18:1(9Z))"

# get different lipid categories
get_lipid_category(lipid)
get_lipid_mainclass(lipid)
get_lipid_subclass(lipid)
```

```{r categories4}
# example lipid Cer(d18:1/18:1(9Z)), LMSP02010003
lipid <- "Cer(d18:1(4E,1OH,3OH)/18:1(9Z))"

# get different lipid categories
get_lipid_category(lipid)
get_lipid_mainclass(lipid)
get_lipid_subclass(lipid)
```


```{r radyl groups}
# example lipid Cer(d18:1/18:1(9Z)), LMSP02010003
lipid <- "Cer(d18:1(4E,1OH,3OH)/18:1(9Z))"

isolate_radyls(lipid)
isolate_sphingoid_base(lipid)
get_hydroxy_groups(lipid)
```

